-- Migration: Add Supabase UUID support to users table
-- Generated by ClinicCore Supabase Migration Plan
-- Run this migration after configuring your Supabase project

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Add supabaseId column to users table (nullable for backward compatibility)
ALTER TABLE users ADD COLUMN IF NOT EXISTS supabaseId UUID;

-- Create unique index for supabaseId (allows NULL values)
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_supabaseId ON users(supabaseId) WHERE supabaseId IS NOT NULL;

-- Update the users table to make openId nullable (for users migrating from legacy auth)
ALTER TABLE users ALTER COLUMN openId DROP NOT NULL;

-- Create profiles table for public user data (linked to Supabase auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('admin', 'receptionist', 'doctor', 'patient')),
  phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS Policies for profiles
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Admins can view all profiles" ON public.profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Function to automatically create profile on Supabase signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', ''),
    NEW.raw_user_meta_data->>'avatar_url',
    'patient'  -- Default role, can be changed by admin
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for automatic profile creation (only if not exists)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Storage bucket for clinic documents (run in Supabase Storage dashboard or via API)
-- The bucket 'clinic-documents' should be created with public access enabled

-- Optional: Create a function to sync existing users to Supabase
CREATE OR REPLACE FUNCTION public.sync_existing_user_to_supabase(p_user_id UUID)
RETURNS void AS $$
DECLARE
  v_email TEXT;
  v_name TEXT;
  v_user_meta JSONB;
BEGIN
  -- Get user data from local users table
  SELECT email, name INTO v_email, v_name
  FROM users
  WHERE supabaseId = p_user_id
  LIMIT 1;

  -- Build metadata
  v_user_meta := jsonb_build_object(
    'full_name', v_name,
    'migrated_from', 'cliniccore'
  );

  -- Note: This is a placeholder. Actual user creation in Supabase Auth
  -- should be done via Supabase Admin API with service role key
  RAISE NOTICE 'User sync placeholder for: %', v_email;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comment describing the migration
COMMENT ON COLUMN users.supabaseId IS 'Supabase Auth UUID, links user to Supabase authentication system';
COMMENT ON COLUMN users.openId IS 'Legacy OAuth ID, kept for backward compatibility during migration';

